name: FinGuard CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Needed for GitHub OIDC authentication with AWS
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the FinGuard code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Authenticate GitHub with AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: YOUR_IAM_ROLE_ARN
          aws-region: YOUR_AWS_REGION

      # 3. Log Docker into Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build the Docker image and tag it with the Git commit SHA
      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fingaurd_ecr
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # 5. Push the image to ECR
      - name: Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fingaurd_ecr
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
